---
- name: Configure host.
  hosts: all
  become: true

  vars_files:
    - config.yaml

  roles:
    - role: storage_setup
      when: storage_setup

    - role: system_setup
      when: system_setup
