---
- name: Change hostname to "{{ username }}"
  hostname:
    name: "{{ username }}"


- name: Copy WoL service
  copy:
    src: wol.service
    dest: /etc/systemd/system/wol@.service

- name: Start and Enable WoL
  service:
    name: "wol@{{ ansible_default_ipv4.interface }}.service"
    enabled: true
    state: started


- name: Set up motd
  copy:
    src: motd.txt
    dest: /etc/motd
    mode: 0644


- name: Remove cockpit motd
  file:
    path: /etc/motd.d/cockpit
    state: absent


- name: Set passwordless sudo for paco
  community.general.sudoers:
    name: allow-all-wheel
    group: wheel
    commands: ALL
    host: ALL
    nopassword: true
    state: present
    validation: required


- name: Tune powertop
  command:
    cmd: powertop --auto-tune


- name: Update sshd config
  copy:
    dest: /etc/ssh/sshd_config.d/00_paco.conf
    mode: 0644
    validate: 'sshd -T -f %s'
    content: |
      PasswordAuthentication no
      PermitRootLogin no
      UseDNS no
      PermitEmptyPasswords no
      ChallengeResponseAuthentication no
      GSSAPIAuthentication no
      X11Forwarding no
  notify: Restart sshd


- name: Stop, Disable, Mask firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: false
    masked: true


- name: Start, Enable iptables
  systemd:
    name: iptables
    state: started
    enabled: true


- name: Set up iptables rules
  copy:
    dest: /etc/sysconfig/iptables
    mode: 0600
    content: |
      *filter
      :INPUT DROP [0:0]
      :FORWARD DROP [0:0]
      :OUTPUT ACCEPT [0:0]
      -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      -A INPUT -i lo -j ACCEPT
      -A INPUT -m conntrack --ctstate INVALID -j DROP
      -A INPUT -p icmp -m icmp --icmp-type 8 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -p udp -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -p tcp --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable
      -A INPUT -p tcp -j REJECT --reject-with tcp-reset
      -A INPUT -j REJECT --reject-with icmp-proto-unreachable
      -A INPUT -p tcp --dport 22 -j ACCEPT
      COMMIT
  notify: Restart iptables


- name: Enable Reverse Path Filter
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    sysctl_file: /etc/sysctl.d/00-paco.conf
    state: present
