---
- name: Create mountpoint
  file:
    path: "{{ nas_mountpoint }}"
    state: directory
    mode: "0770"
    owner: "{{ nas_user }}"
    group: "{{ nas_user }}"


- name: Create fstab entry and mount root subvolume
  mount:
    src: "LABEL={{ nas_device_label }}"
    path: "{{ nas_mountpoint }}"
    fstype: btrfs
    opts: defaults,noatime,subvol=@,compress=zstd:1
    dump: 0
    passno: 0
    state: mounted
  notify: Reload systemd daemon

- name: Create fstab entries and mount subvolumes
  mount:
    src: "LABEL={{ nas_device_label }}"
    path: "{{ nas_mountpoint }}/{{ item.value }}"
    fstype: btrfs
    opts: "defaults,noatime,subvol=@{{ item.key }},compress=zstd:1"
    dump: 0
    passno: 0
    state: mounted
  loop: "{{ btrfs_subvolumes | dict2items }}"
  notify: Reload systemd daemon


- name: Chown subdirectories of "{{ nas_mountpoint }}"
  file:
    path: "{{ nas_mountpoint }}/{{ item.value }}"
    state: directory
    owner: "{{ nas_user }}"
    group: "{{ nas_user }}"
  loop: "{{ btrfs_subvolumes | dict2items }}"
