---
- name: Create btrfs root subvolume
  community.general.btrfs_subvolume:
    name: /@
    automount: true
    filesystem_label: "{{ nas_device_label }}"

- name: Create btrfs subvolumes
  community.general.btrfs_subvolume:
    name: "/@{{ item.key }}"
    automount: true
    filesystem_label: "{{ nas_device_label }}"
  loop: "{{ btrfs_subvolumes | dict2items }}"
