---
- name: Create root subvolume
  community.general.btrfs_subvolume:
    name: /@
    automount: true
    filesystem_label: "{{ nas_device_label }}"

- name: Create snapshots subvolume
  community.general.btrfs_subvolume:
    name: /@snapshots
    automount: true
    filesystem_label: "{{ nas_device_label }}"

- name: Create docker subvolume
  community.general.btrfs_subvolume:
    name: /@docker
    automount: true
    filesystem_label: "{{ nas_device_label }}"

- name: Create images subvolume
  community.general.btrfs_subvolume:
    name: /@images
    automount: true
    filesystem_label: "{{ nas_device_label }}"

- name: Create videos subvolume
  community.general.btrfs_subvolume:
    name: /@videos
    automount: true
    filesystem_label: "{{ nas_device_label }}"

- name: Create documents subvolume
  community.general.btrfs_subvolume:
    name: /@documents
    automount: true
    filesystem_label: "{{ nas_device_label }}"

- name: Create media subvolume
  community.general.btrfs_subvolume:
    name: /@media
    automount: true
    filesystem_label: "{{ nas_device_label }}"
