---
- name: Create mountpoint
  file:
    path: "{{ nas_mountpoint }}"
    state: directory
    mode: "0770"
    owner: "{{ nas_user }}"
    group: "{{ nas_user }}"


- name: Mount FS
  mount:
    src: "LABEL={{ nas_device_label }}"
    path: "{{ nas_mountpoint }}"
    fstype: btrfs
    state: ephemeral
  notify: 
    - Unmount FS


- name: Create root subvolume
  community.general.btrfs_subvolume:
    name: "{{ nas_mountpoint }}/@"
    filesystem_label: "{{ nas_device_label }}"

- name: Create snapshots subvolume
  community.general.btrfs_subvolume:
    name: "{{ nas_mountpoint }}/@snapshots"
    filesystem_label: "{{ nas_device_label }}"

- name: Create docker subvolume
  community.general.btrfs_subvolume:
    name: "{{ nas_mountpoint }}/@docker"
    filesystem_label: "{{ nas_device_label }}"

- name: Create images subvolume
  community.general.btrfs_subvolume:
    name: "{{ nas_mountpoint }}/@images"
    filesystem_label: "{{ nas_device_label }}"

- name: Create videos subvolume
  community.general.btrfs_subvolume:
    name: "{{ nas_mountpoint }}/@videos"
    filesystem_label: "{{ nas_device_label }}"

- name: Create documents subvolume
  community.general.btrfs_subvolume:
    name: "{{ nas_mountpoint }}/@documents"
    filesystem_label: "{{ nas_device_label }}"

- name: Create media subvolume
  community.general.btrfs_subvolume:
    name: "{{ nas_mountpoint }}/@media"
    filesystem_label: "{{ nas_device_label }}"
