---
- name: Add docker repository
  command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - shadow-utils
      - fuse-overlayfs

- name: Install docker rootless
  become: true
  become_user: "{{ docker_username }}"
  environment:
    - XDG_RUNTIME_DIR: "/run/user/{{ docker_username_uid }}"
  command:
    cmd: /usr/bin/dockerd-rootless-setuptool.sh install
    creates: ~/.config/systemd/user/docker.service

- name: Ensure docker data parent "{{ docker_data_parent }}" exists
  file:
    path: "{{ docker_data_parent }}"
    owner: "{{ docker_username }}"
    group: "{{ docker_username }}"
    state: directory

- name: Ensure docker data root "{{ docker_data_root }}" exists
  file:
    path: "{{ docker_data_root }}"
    owner: "{{ docker_username }}"
    group: "{{ docker_username }}"
    state: directory

- name: Allow exposing privileged ports to docker
  capabilities:
    path: /usr/bin/rootlesskit
    capability: cap_net_bind_service+ep
    state: present

- name: Add user "{{ username }}" to group of docker "{{ docker_username }}"
  user:
    name: "{{ username }}"
    groups: "{{ docker_username }}"
    append: yes

- name: Update docker rootless systemd service file
  block:
    - name: Set custom data-root
      ini_file:
        path: "/home/{{ docker_username }}/.config/systemd/user/docker.service"
        section: Service
        option: ExecStart
        value: /usr/bin/dockerd-rootless.sh --data-root /nas/docker -H unix:///tmp/docker.sock
        owner: "{{ docker_username }}"
        group: "{{ docker_username }}"
        state: present
        no_extra_spaces: true
        exclusive: true
    - name: Change socket ownership
      ini_file:
        path: "/home/{{ docker_username }}/.config/systemd/user/docker.service"
        section: Service
        option: ExecStartPost
        value: chown "{{ docker_username }}:{{ docker_username }}" /tmp/docker.sock
        owner: "{{ docker_username }}"
        group: "{{ docker_username }}"
        state: present
        no_extra_spaces: true
        exclusive: false

- name: Start and Enable docker rootless
  become: true
  become_user: "{{ docker_username }}"
  environment:
    - XDG_RUNTIME_DIR: "/run/user/{{ docker_username_uid }}"
  systemd:
    name: docker
    scope: user
    enabled: true
    state: started
  notify: Reload systemd user daemon

- name: Enable lingering for "{{ docker_username }}"
  command:
    cmd: "loginctl enable-linger {{ docker_username }}"
    creates: "/var/lib/systemd/linger/{{ docker_username }}"
