---
- name: Stop, Disable, Mask firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: false
    masked: true

- name: Start, Enable iptables
  systemd:
    name: iptables
    state: started
    enabled: true

- name: Set up iptables rules
  template:
    src: iptables.jinja2
    dest: /etc/sysconfig/iptables
    mode: 0600
  notify: Restart iptables

- name: Set rp_filter kernel parameter
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    sysctl_file: /etc/sysctl.d/00-rp_filter.conf
    state: present
