---
- name: Install Groups
  package:
    name:
      - '@Standard'
      - '@Headless Management'
      - '@Server product core'
      - '@Common NetworkManager submodules'
      - '@Console Internet Tools'
      - '@Development Tools'
      - '@RPM Development Tools'
      - '@Hardware Monitoring Utilities'
    state: present

- name: Install Packages
  package:
    name:
      - iperf3
      - iptables-utils
      - iptables-nft-services
      - powertop
    state: present
