---
- name: Update sshd config
  template:
    src: sshd_config.jinja2
    dest: /etc/ssh/sshd_config.d/00_paco.conf
    validate: 'sshd -T -f %s'
  notify: 
    - Restart sshd
    - SELinux new sshd port

- name: Tune powertop
  command:
    cmd: powertop --auto-tune

- name: Copy WoL service
  copy:
    src: wol.service
    dest: /etc/systemd/system/wol@.service

- name: Start and Enable WoL
  service:
    name: "wol@{{ ansible_default_ipv4.interface }}.service"
    enabled: true
    state: started

- name: Set up motd
  copy:
    src: motd.txt
    dest: /etc/motd
    mode: 0644

- name: Remove cockpit motd
  file:
    path: /etc/motd.d/cockpit
    state: absent
