---
- name: Update sshd config
  copy:
    dest: /etc/ssh/sshd_config.d/00_paco.conf
    mode: 0644
    validate: 'sshd -T -f %s'
    content: |
      PasswordAuthentication no
      PermitRootLogin no
      UseDNS no
      PermitEmptyPasswords no
      ChallengeResponseAuthentication no
      GSSAPIAuthentication no
      X11Forwarding no
  notify: Restart sshd

- name: Tune powertop
  command:
    cmd: powertop --auto-tune

- name: Copy WoL service
  copy:
    src: wol.service
    dest: /etc/systemd/system/wol@.service

- name: Start and Enable WoL
  service:
    name: "wol@{{ ansible_default_ipv4.interface }}.service"
    enabled: true
    state: started

- name: Set up motd
  copy:
    src: motd.txt
    dest: /etc/motd
    mode: 0644

- name: Remove cockpit motd
  file:
    path: /etc/motd.d/cockpit
    state: absent
