---
- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart iptables
  service: 
    name: iptables
    state: restarted

- name: Restart docker
  become: true
  become_user: "{{ docker_username }}"
  environment:
    - XDG_RUNTIME_DIR: "/run/user/{{ docker_username_uid }}"
  systemd:
    name: docker
    scope: user
    state: restarted

- name: Reload systemd user daemon
  become: true
  become_user: "{{ docker_username }}"
  environment:
    - XDG_RUNTIME_DIR: "/run/user/{{ docker_username_uid }}"
  systemd:
    daemon_reload: true
    scope: user
    
- name: Rebuild initramfs
  command:
    cmd: dracut --hostonly --force

- name: SELinux new sshd port
  seport:
    ports: "{{ ssh_port }}"
    proto: tcp
    setype: ssh_port_t
    state: present
