---
- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart iptables
  service: 
    name: iptables
    state: restarted

- name: Restart docker
  systemd:
    name: docker
    scope: user
    state: restarted
  become: false

- name: Reload systemd user daemon
  systemd:
    daemon_reload: true
    scope: user
  become: false
    
- name: Rebuild initramfs
  command:
    cmd: dracut --hostonly --force

- name: SELinux new sshd port
  seport:
    ports: "{{ ssh_port }}"
    proto: tcp
    setype: ssh_port_t
    state: present
